# Generated by Django 4.2.16 on 2025-05-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('login', '로그인'), ('news_view', '뉴스 조회'), ('video_watch', '영상 시청'), ('stock_search', '주식 검색'), ('saving_search', '예적금 검색'), ('community_post', '커뮤니티 글 작성'), ('community_comment', '댓글 작성'), ('survey_completed', '설문조사 완료')], max_length=20),
        ),
    ]
