# Generated by Django 4.2.13 on 2025-05-25 03:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('url', models.URLField(unique=True)),
                ('published_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(default='Naver Finance', max_length=100)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
