# Generated by Django 4.2.16 on 2025-05-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingproducts',
            name='recommendations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='savingproducts',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
