# Generated by Django 4.2.16 on 2025-05-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=20, unique=True, verbose_name='종목코드')),
                ('stock_name', models.CharField(max_length=100, verbose_name='종목명')),
            ],
            options={
                'verbose_name': '주식 정보',
                'verbose_name_plural': '주식 정보 목록',
                'ordering': ['stock_name'],
            },
        ),
    ]
