# Generated by Django 4.2.16 on 2025-05-26 05:26

from django.db import migrations

# 샘플 주식 데이터
SAMPLE_STOCKS = [
    {"stock_code": "005930", "stock_name": "삼성전자"},
    {"stock_code": "000660", "stock_name": "SK하이닉스"},
    {"stock_code": "035420", "stock_name": "NAVER"},
    {"stock_code": "035720", "stock_name": "카카오"},
    {"stock_code": "005380", "stock_name": "현대차"},
    {"stock_code": "000270", "stock_name": "기아"},
    {"stock_code": "051910", "stock_name": "LG화학"},
    {"stock_code": "006400", "stock_name": "삼성SDI"},
    {"stock_code": "207940", "stock_name": "삼성바이오로직스"},
    {"stock_code": "068270", "stock_name": "셀트리온"},
    {"stock_code": "003670", "stock_name": "포스코퓨처엠"},
    {"stock_code": "005490", "stock_name": "POSCO홀딩스"},
    {"stock_code": "028260", "stock_name": "삼성물산"},
    {"stock_code": "105560", "stock_name": "KB금융"},
    {"stock_code": "055550", "stock_name": "신한지주"},
    {"stock_code": "066570", "stock_name": "LG전자"},
    {"stock_code": "017670", "stock_name": "SK텔레콤"},
    {"stock_code": "032830", "stock_name": "삼성생명"},
    {"stock_code": "096770", "stock_name": "SK이노베이션"},
    {"stock_code": "012330", "stock_name": "현대모비스"},
]


def seed_data(apps, schema_editor):
    Stock = apps.get_model("main", "Stock")
    for stock_data in SAMPLE_STOCKS:
        Stock.objects.create(
            stock_code=stock_data["stock_code"], stock_name=stock_data["stock_name"]
        )


def reverse_seed_data(apps, schema_editor):
    Stock = apps.get_model("main", "Stock")
    for stock_data in SAMPLE_STOCKS:
        Stock.objects.filter(stock_code=stock_data["stock_code"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(seed_data, reverse_seed_data),
    ]
