# Generated by Django 4.2.16 on 2025-05-25 08:18

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('home_address', models.CharField(blank=True, max_length=255, null=True)),
                ('company_address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('birth', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_number', models.CharField(blank=True, max_length=50, null=True)),
                ('stock_experience', models.CharField(blank=True, choices=[('none', '없음'), ('beginner', '초보 (1년 미만)'), ('intermediate', '중급 (1-3년)'), ('advanced', '고급 (3년 이상)')], max_length=20, null=True)),
                ('investment_style', models.CharField(blank=True, choices=[('conservative', '안전형'), ('moderate', '중립형'), ('aggressive', '공격형')], max_length=20, null=True)),
                ('monthly_investment_amount', models.CharField(blank=True, choices=[('under_50', '50만원 미만'), ('50_100', '50-100만원'), ('100_300', '100-300만원'), ('over_300', '300만원 이상')], max_length=20, null=True)),
                ('investment_goal', models.CharField(blank=True, choices=[('short_term', '단기 수익'), ('long_term', '장기 투자'), ('retirement', '은퇴 준비'), ('emergency_fund', '비상 자금')], max_length=30, null=True)),
                ('owned_stocks', models.JSONField(blank=True, default=list)),
                ('interested_stocks', models.JSONField(blank=True, default=list)),
                ('watch_later_videos', models.JSONField(blank=True, default=list)),
                ('subscribed_channels', models.JSONField(blank=True, default=list)),
                ('survey_completed', models.BooleanField(default=False)),
                ('survey_completed_date', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', '로그인'), ('news_view', '뉴스 조회'), ('video_watch', '영상 시청'), ('stock_search', '주식 검색'), ('saving_search', '예적금 검색'), ('community_post', '커뮤니티 글 작성'), ('community_comment', '댓글 작성')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=20)),
                ('stock_name', models.CharField(max_length=100)),
                ('recommendation_reason', models.TextField()),
                ('confidence_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavingRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=50)),
                ('interest_rate', models.FloatField()),
                ('product_type', models.CharField(choices=[('deposit', '예금'), ('saving', '적금')], max_length=20)),
                ('recommendation_reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
